# Generated by Django 4.1.5 on 2023-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('no_of_centers', models.IntegerField()),
                ('timing', models.CharField(max_length=30)),
            ],
        ),
    ]
