# Generated by Django 4.1.5 on 2023-04-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_centers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centers',
            old_name='name',
            new_name='center_name',
        ),
    ]
