# Generated by Django 4.1.5 on 2023-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_centers_center_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vaccine', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
    ]
